// apps/web/src/App.tsx
import { useAuth } from "./hooks/useAuth";
import { useTelegram } from "./hooks/useTelegram";
import { useStore } from "./stores/useStore";
import Dashboard from "./components/Dashboard";
import BudgetManager from "./components/BudgetManager";
import TransactionList from "./components/TransactionList";
import GoogleIntegration from "./components/GoogleIntegration";
import { TelegramLoginButton } from "./components/TelegramLoginButton";
import { setupSwipeBehavior } from "./utils/telegramBridge";
import { useEffect, useState, useRef } from "react";

type Tab = "dashboard" | "budget" | "transactions" | "google";

const BOT_USERNAME = import.meta.env.VITE_BOT_USERNAME;

function App() {
    const { ready, expand, webApp, requestFullscreen } = useTelegram();
    const { token, authenticated, loading: authLoading } = useAuth();
    const { budget } = useStore();

    const setToken = useStore((state) => state.setToken);
    const fetchBudget = useStore((state) => state.fetchBudget);
    const fetchTransactions = useStore((state) => state.fetchTransactions);

    const [activeTab, setActiveTab] = useState<Tab>("dashboard");
    const [uiReady, setUiReady] = useState(false);
    const [isMiniApp, setIsMiniApp] = useState(false);
    const [isLoggingIn, setIsLoggingIn] = useState(false);
    const [loginError, setLoginError] = useState<string | null>(null);

    const hasExpanded = useRef(false);
    const hasFetched = useRef(false);
    const hasRequestedFullscreen = useRef(false); // ✅ Prevent infinite loop

    // Check if running inside Telegram Mini App
    useEffect(() => {
        const isInTelegram = !!webApp;
        setIsMiniApp(isInTelegram);
        console.log("Running in Telegram Mini App:", isInTelegram);
    }, [webApp]);

    // ✅ Initialize Mini App (only once)
    useEffect(() => {
        if (isMiniApp && ready && !hasExpanded.current) {
            hasExpanded.current = true;

            setTimeout(() => {
                // Expand viewport
                expand?.();

                // Disable vertical swipe to prevent app closing on scroll
                setupSwipeBehavior(false);
                console.log("✅ Disabled vertical swipe behavior");

                // Request fullscreen ONCE (optional - remove if you don't want auto-fullscreen)
                if (!hasRequestedFullscreen.current) {
                    hasRequestedFullscreen.current = true;
                    // Uncomment if you want auto-fullscreen:
                    // requestFullscreen();
                }

                setUiReady(true);
            }, 150);
        } else if (!isMiniApp) {
            setUiReady(true);
        }
    }, [isMiniApp, ready, expand, requestFullscreen]);

    // ✅ Set token in store when authenticated
    useEffect(() => {
        if (token) {
            setToken(token);
        }
    }, [token, setToken]);

    // ✅ Fetch budget/transactions in background
    useEffect(() => {
        if (authenticated && !hasFetched.current) {
            hasFetched.current = true;
            fetchBudget()
                .then(() => fetchTransactions())
                .catch((error) => {
                    console.error("Error fetching data:", error);
                    hasFetched.current = false;
                });
        }
    }, [authenticated, fetchBudget, fetchTransactions]);

    // Handle Telegram Widget Login
    const handleTelegramAuth = async (telegramUser: {
        id: number;
        first_name: string;
        last_name?: string;
        username?: string;
        photo_url?: string;
        auth_date: number;
        hash: string;
    }) => {
        setIsLoggingIn(true);
        setLoginError(null);

        try {
            console.log("Telegram Widget user data:", telegramUser);

            const response = await fetch("/api/auth/telegram-widget", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(telegramUser),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || "Authentication failed");
            }

            console.log("Widget auth successful:", data);

            if (data.token) {
                setToken(data.token);
                localStorage.setItem("auth_token", data.token);
            }
        } catch (error) {
            console.error("Error during Telegram widget login:", error);
            const errorMessage = error instanceof Error ? error.message : "Login gagal. Silakan coba lagi.";
            setLoginError(errorMessage);
        } finally {
            setIsLoggingIn(false);
        }
    };

    // Loading / skeleton UI
    if (!uiReady || authLoading) {
        return (
            <div className="flex flex-col items-center justify-center min-h-screen gap-4 p-4 bg-base-100 text-base-content">
                <span className="loading loading-spinner loading-lg"></span>
                <p className="text-sm text-base-content text-opacity-70">Memuat...</p>
            </div>
        );
    }

    // Not authenticated - Show login page
    if (!authenticated) {
        return (
            <div className="flex flex-col items-center justify-center min-h-screen gap-6 p-4 bg-base-200">
                <div className="bg-base-100 rounded-2xl shadow-xl p-8 max-w-md w-full">
                    <div className="text-center mb-6">
                        <div className="text-6xl mb-4">💰</div>
                        <h1 className="text-2xl font-bold text-base-content">Kodetama Finance</h1>
                        <p className="text-base-content text-opacity-70 text-sm mt-2">
                            Kelola keuangan Anda dengan mudah
                        </p>
                    </div>

                    {loginError && (
                        <div className="alert alert-error mb-4">
                            <span>❌</span>
                            <span>{loginError}</span>
                        </div>
                    )}

                    {!isMiniApp && !loginError && (
                        <div className="alert alert-info mb-4">
                            <span>ℹ️</span>
                            <span>
                                Anda juga bisa membuka aplikasi ini dari bot Telegram untuk pengalaman yang lebih baik.
                            </span>
                        </div>
                    )}

                    <div className="space-y-4">
                        <div className="text-center">
                            <div className="text-sm text-base-content text-opacity-80 mb-4">
                                Login dengan akun Telegram Anda:
                            </div>
                            {isLoggingIn ? (
                                <div className="flex flex-col items-center gap-2 py-4">
                                    <span className="loading loading-spinner loading-md"></span>
                                    <p className="text-sm text-base-content text-opacity-70">Memproses login...</p>
                                </div>
                            ) : (
                                <TelegramLoginButton
                                    botName={BOT_USERNAME}
                                    buttonSize="large"
                                    cornerRadius={10}
                                    requestAccess={true}
                                    usePic={true}
                                    lang="en"
                                    onAuth={handleTelegramAuth}
                                />
                            )}
                        </div>

                        <div className="divider">atau</div>

                        <div className="card card-compact bg-base-200">
                            <div className="card-body text-center">
                                <div className="text-sm text-base-content text-opacity-80 mb-2">
                                    Gunakan di Telegram Mini App
                                </div>
                                <a
                                    href={`https://t.me/${BOT_USERNAME}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="btn btn-primary btn-sm"
                                >
                                    <span>Buka Bot</span>
                                    <span>→</span>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div className="mt-6 text-center">
                        <p className="text-xs text-base-content text-opacity-50">
                            Dengan login, Anda menyetujui penggunaan data Telegram Anda
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    // ✅ Main UI (Authenticated)
    return (
        <div className="min-h-screen bg-base-100 text-base-content transition-colors duration-300">
            {/* Header - Fixed at top */}
            <header className="fixed left-0 right-0 z-10 text-primary-content bg-base-200 p-4 shadow-lg">
                <div className="flex items-center gap-3">
                    <div className="flex-1 text-center">
                        <h1 className="font-semibold">Periode</h1>
                        <p className="text-sm text-primary-content text-opacity-80">
                            {budget?.period.name ?? "Dashboard"}
                        </p>
                    </div>
                    {/* Logout button */}
                    {!isMiniApp && (
                        <button
                            onClick={() => {
                                setToken("");
                                localStorage.removeItem("auth_token");
                                window.location.reload();
                            }}
                            className="btn btn-ghost btn-sm text-primary-content text-opacity-80 hover:text-primary-content"
                        >
                            Keluar
                        </button>
                    )}
                </div>
            </header>

            {/* Content */}
            <main className="min-h-screen pt-36 pb-28 px-4 overflow-y-auto">
                {activeTab === "dashboard" && <Dashboard />}
                {activeTab === "budget" && <BudgetManager />}
                {activeTab === "transactions" && <TransactionList />}
                {activeTab === "google" && <GoogleIntegration />}
            </main>

            {/* Bottom Navigation - Fixed at bottom */}
            <div className="fixed bottom-0 left-0 right-0 z-10 flex pt-4 pb-10 bg-base-200 border-t border-base-300">
                <NavButton
                    icon="Dashboard"
                    label="Dashboard"
                    active={activeTab === "dashboard"}
                    onClick={() => setActiveTab("dashboard")}
                />
                <NavButton
                    icon="Budget"
                    label="Budget"
                    active={activeTab === "budget"}
                    onClick={() => setActiveTab("budget")}
                />
                <NavButton
                    icon="Transaksi"
                    label="Transaksi"
                    active={activeTab === "transactions"}
                    onClick={() => setActiveTab("transactions")}
                />
                <NavButton
                    icon="Google"
                    label="Google"
                    active={activeTab === "google"}
                    onClick={() => setActiveTab("google")}
                />
            </div>
        </div>
    );
}

function NavButton({ icon, label, active, onClick }: {
    icon: string;
    label: string;
    active: boolean;
    onClick: () => void
}) {
    const icons: Record<string, JSX.Element> = {
        Google: (
            <path
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0 0a8.949 8.949 0 0 0 4.951-1.488A3.987 3.987 0 0 0 13 16h-2a3.987 3.987 0 0 0-3.951 3.512A8.948 8.948 0 0 0 12 21Zm3-11a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
            />
        ),
        Dashboard: (
            <path
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 4v15a1 1 0 0 0 1 1h15M8 16l2.5-5.5 3 3L17.273 7 20 9.667"
            />
        ),
        Budget: (
            <path
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M17 8H5m12 0a1 1 0 0 1 1 1v2.6M17 8l-4-4M5 8a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.6M5 8l4-4 4 4m6 4h-4a2 2 0 1 0 0 4h4a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1Z"
            />
        ),
        Transaksi: (
            <path
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M5 19V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v13H7a2 2 0 0 0-2 2Zm0 0a2 2 0 0 0 2 2h12M9 3v14m7 0v4"
            />
        ),
    };

    return (
        <button
            onClick={onClick}
            className={`${active ? "text-primary" : "text-base-content"} flex flex-col items-center gap-1 flex-1`}
        >
            <svg
                className={`w-6 h-6 ${active ? "text-primary" : "text-base-content"}`}
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                fill="none"
                viewBox="0 0 24 24"
            >
                {icons[icon]}
            </svg>
            <span className="text-xs">{label}</span>
        </button>
    );
}

export default App;

// apps/web/src/App.vue
<template>
    <div class="min-h-screen bg-base-100 text-base-content transition-colors duration-300">
        <!-- Loading / skeleton UI -->
        <LoadingSkeleton v-if="!uiReady || authLoading" />

        <!-- Login Page -->
        <LoginPage
            v-else-if="!authenticated"
            :bot-username="BOT_USERNAME"
            :is-mini-app="isMiniApp"
            :login-error="loginError"
            :is-logging-in="isLoggingIn"
            @auth="handleTelegramAuth"
        />

        <!-- Main UI (Authenticated) -->
        <AuthenticatedLayout
            v-else
            :budget="budget"
            :is-mini-app="isMiniApp"
            @logout="handleLogout"
        />
    </div>
</template>

<script setup lang="ts">
import { ref, onBeforeMount, onMounted, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useStore } from './stores/useStore'
import { useAuth } from './composables/useAuth'
import { useTelegram } from './composables/useTelegram'
import LoadingSkeleton from './components/LoadingSkeleton.vue'
import LoginPage from './components/LoginPage.vue'
import AuthenticatedLayout from './components/AuthenticatedLayout.vue'
import { setupSwipeBehavior } from './utils/telegramBridge'

const BOT_USERNAME = import.meta.env.VITE_BOT_USERNAME;

const { ready, expand, webApp, requestFullscreen } = useTelegram();
const { token: authToken, authenticated, loading: authLoading } = useAuth();
const store = useStore();
const { budget } = storeToRefs(store);

const uiReady = ref(false);
const isMiniApp = ref(false);
const isLoggingIn = ref(false);
const loginError = ref<string | null>(null);
const hasExpanded = ref(false);
const hasFetched = ref(false);
const hasRequestedFullscreen = ref(false);

// Check if running inside Telegram Mini App
onBeforeMount(() => {
    isMiniApp.value = !!webApp.value;
    console.log("Running in Telegram Mini App:", isMiniApp.value);
    console.log("WebApp object:", webApp.value);
    console.log("Telegram WebApp:", window.Telegram?.WebApp);
});

// Initialize Mini App (only once)
watch([isMiniApp, ready], async () => {
    console.log("Watch triggered - isMiniApp:", isMiniApp.value, "ready:", ready.value);

    if (isMiniApp.value && ready.value && !hasExpanded.value) {
        hasExpanded.value = true;
        console.log("🚀 Initializing Telegram Mini App");

        await new Promise(resolve => setTimeout(resolve, 150));

        // Expand viewport
        expand?.();

        // Disable vertical swipe to prevent app closing on scroll
        setupSwipeBehavior(false);
        console.log("✅ Disabled vertical swipe behavior");

        // Request fullscreen ONCE (optional - remove if you don't want auto-fullscreen)
        if (!hasRequestedFullscreen.value) {
            hasRequestedFullscreen.value = true;
            // Uncomment if you want auto-fullscreen:
            requestFullscreen();
        }

        uiReady.value = true;
        console.log("✅ Mini App ready, setting uiReady to true");
    } else if (!isMiniApp.value) {
        console.log("🌐 Not in Mini App, setting uiReady to true");
        uiReady.value = true;
    }
});

// Fallback: If Mini App initialization takes too long, show UI anyway
watch([authenticated, authLoading], () => {
    console.log("Auth state changed - authenticated:", authenticated.value, "loading:", authLoading.value);
});

onMounted(() => {
    // Safety timeout: If uiReady is still false after 5 seconds, set it to true
    setTimeout(() => {
        if (!uiReady.value) {
            console.log("🚨 Safety timeout: Forcing uiReady to true");
            uiReady.value = true;
        }
    }, 5000);
});

// Set token in store when authenticated
watch(authToken, () => {
    if (authToken.value) {
        store.setToken(authToken.value);
    }
});

// Fetch budget/transactions in background
watch([authenticated, budget], () => {
    if (authenticated.value && !hasFetched.value) {
        hasFetched.value = true;
        store.fetchBudget()
            .then(() => store.fetchTransactions())
            .catch((error) => {
                console.error("Error fetching data:", error);
                hasFetched.value = false;
            });
    }
});

// Handle Telegram Widget Login
const handleTelegramAuth = async (telegramUser: {
    id: number;
    first_name: string;
    last_name?: string;
    username?: string;
    photo_url?: string;
    auth_date: number;
    hash: string;
}) => {
    isLoggingIn.value = true;
    loginError.value = null;

    try {
        console.log("Telegram Widget user data:", telegramUser);

        const response = await fetch("/api/auth/telegram-widget", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(telegramUser),
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || "Authentication failed");
        }

        console.log("Widget auth successful:", data);

        if (data.token) {
            store.setToken(data.token);
            localStorage.setItem("auth_token", data.token);
        }
    } catch (error) {
        console.error("Error during Telegram widget login:", error);
        const errorMessage = error instanceof Error ? error.message : "Login gagal. Silakan coba lagi.";
        loginError.value = errorMessage;
    } finally {
        isLoggingIn.value = false;
    }
};

const handleLogout = () => {
    store.setToken("");
    localStorage.removeItem("auth_token");
    window.location.reload();
};
</script>

<script lang="ts">
import NavButton from './components/NavButton.vue'

export default {
    components: { NavButton }
}
</script>
