// apps/web/src/components/BudgetManager.vue
<template>
    <div class="space-y-4">
        <!-- Loading skeleton -->
        <div v-if="!budget" class="animate-pulse h-40 bg-base-200 rounded-2xl" />

        <!-- Main content -->
        <div v-else>
            <!-- Period Header -->
            <div class="card card-compact bg-base-200 bg-opacity-50">
                <div class="card-body">
                    <div class="flex items-center justify-between">
                        <div>
                            <div class="text-sm text-base-content text-opacity-70">Periode</div>
                            <div class="font-semibold">{{ budget.period.name }}</div>
                        </div>
                        <button
                            @click="toggleEditing"
                            :class="`btn btn-sm ${editing ? 'btn-outline' : 'btn-primary'}`"
                        >
                            {{ editing ? "Batal" : "Edit" }}
                        </button>
                    </div>
                </div>
            </div>

            <!-- Income -->
            <div class="card card-compact bg-base-200 bg-opacity-50">
                <div class="card-body">
                    <div class="text-sm text-base-content text-opacity-70">Penghasilan Bulanan</div>
                    <input
                        v-if="editing"
                        v-model.number="localIncome"
                        type="number"
                        class="input input-bordered w-full"
                    />
                    <div v-else class="text-2xl font-bold text-primary">
                        {{ formatRupiah(localIncome) }}
                    </div>
                </div>
            </div>

            <!-- Budget Allocation -->
            <div class="card card-compact bg-base-200 bg-opacity-50">
                <div class="card-body space-y-4">
                    <h3 class="card-title text-base-content">Alokasi Budget (Total: 100%)</h3>

                    <AllocationSlider
                        icon="🏠"
                        label="Needs"
                        v-model="localNeeds"
                        :amount="localIncome * (localNeeds / 100)"
                        :disabled="!editing"
                        :max="100 - localWants"
                        color="success"
                    />

                    <AllocationSlider
                        icon="🎮"
                        label="Wants"
                        v-model="localWants"
                        :amount="localIncome * (localWants / 100)"
                        :disabled="!editing"
                        :max="100 - localNeeds"
                        color="warning"
                    />

                    <AllocationSlider
                        icon="💵"
                        label="Savings"
                        :model-value="localSavings"
                        :amount="localIncome * (localSavings / 100)"
                        :disabled="true"
                        :max="100"
                        color="info"
                    />

                    <button
                        v-if="editing"
                        @click="handleSave"
                        class="btn btn-primary w-full"
                        :disabled="isSaving"
                    >
                        <span v-if="isSaving" class="loading loading-spinner loading-sm"></span>
                        {{ isSaving ? "Menyimpan..." : "Simpan Perubahan" }}
                    </button>
                </div>
            </div>

            <!-- Tips -->
            <div class="alert alert-info">
                <span>💡</span>
                <div>
                    <div class="font-medium">Tips</div>
                    <div class="text-sm text-base-content text-opacity-80">
                        Setiap rupiah harus punya tujuan.
                        Alokasikan 50% untuk needs, 30% untuk wants, dan 20% untuk savings.
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { storeToRefs } from 'pinia';
import { useStore } from '../stores/useStore';
import AllocationSlider from './AllocationSlider.vue';

const store = useStore();
const { budget } = storeToRefs(store);

const editing = ref(false);
const localNeeds = ref(budget.value?.needsPercentage ?? 50);
const localWants = ref(budget.value?.wantsPercentage ?? 30);
const localIncome = ref(budget.value?.estimatedIncome ?? 0);
const isSaving = ref(false);

const localSavings = computed(() => 100 - localNeeds.value - localWants.value);

const toggleEditing = () => {
    editing.value = !editing.value;
    if (!editing.value) {
        // Reset to original values when canceling
        localNeeds.value = budget.value?.needsPercentage ?? 50;
        localWants.value = budget.value?.wantsPercentage ?? 30;
        localIncome.value = budget.value?.estimatedIncome ?? 0;
    }
};

const handleSave = async () => {
    isSaving.value = true;
    try {
        await store.updateBudget({
            estimatedIncome: localIncome.value,
            needsPercentage: localNeeds.value,
            wantsPercentage: localWants.value,
            savingsPercentage: localSavings.value,
            needsAmount: Math.round(localIncome.value * (localNeeds.value / 100)),
            wantsAmount: Math.round(localIncome.value * (localWants.value / 100)),
            savingsAmount: Math.round(localIncome.value * (localSavings.value / 100)),
        });
        editing.value = false;
    } catch (error) {
        console.error('Failed to save budget:', error);
    } finally {
        isSaving.value = false;
    }
};

// Watch for budget changes to update local values
watch(budget, (newBudget) => {
    if (newBudget) {
        localNeeds.value = newBudget.needsPercentage ?? 50;
        localWants.value = newBudget.wantsPercentage ?? 30;
        localIncome.value = newBudget.estimatedIncome ?? 0;
    }
}, { immediate: true });

function formatRupiah(amount: number): string {
    return new Intl.NumberFormat("id-ID", {
        style: "currency",
        currency: "IDR",
        minimumFractionDigits: 0,
    }).format(amount);
}
</script>

// apps/web_old/src/components/BudgetManager.tsx
import { useStore } from "../stores/useStore";
import { useState } from "react";

function formatRupiah(amount: number): string {
    return new Intl.NumberFormat("id-ID", {
        style: "currency",
        currency: "IDR",
        minimumFractionDigits: 0,
    }).format(amount);
}

export default function BudgetManager() {
    const { budget, updateBudget } = useStore();
    const [editing, setEditing] = useState(false);
    const [needs, setNeeds] = useState(budget?.needsPercentage ?? 50);
    const [wants, setWants] = useState(budget?.wantsPercentage ?? 30);
    const [income, setIncome] = useState(budget?.estimatedIncome ?? 0);

    if (!budget) {
        return <div className="animate-pulse h-40 bg-base-200 rounded-2xl" />;
    }

    const savings = 100 - needs - wants;

    const handleSave = async () => {
        await updateBudget({
            estimatedIncome: income,
            needsPercentage: needs,
            wantsPercentage: wants,
            savingsPercentage: savings,
            needsAmount: Math.round(income * (needs / 100)),
            wantsAmount: Math.round(income * (wants / 100)),
            savingsAmount: Math.round(income * (savings / 100)),
        });
        setEditing(false);
    };

    return (
        <div className="space-y-4">
            {/* Period Header */}
            <div className="card card-compact bg-base-200 bg-opacity-50">
                <div className="card-body">
                    <div className="flex items-center justify-between">
                        <div>
                            <div className="text-sm text-base-content text-opacity-70">Periode</div>
                            <div className="font-semibold">{budget.period.name}</div>
                        </div>
                        <button
                            onClick={() => setEditing(!editing)}
                            className={`btn btn-sm ${editing ? 'btn-outline' : 'btn-primary'}`}
                        >
                            {editing ? "Batal" : "Edit"}
                        </button>
                    </div>
                </div>
            </div>

            {/* Income */}
            <div className="card card-compact bg-base-200 bg-opacity-50">
                <div className="card-body">
                    <div className="text-sm text-base-content text-opacity-70">Penghasilan Bulanan</div>
                    {editing ? (
                        <input
                            type="number"
                            value={income}
                            onChange={(e) => setIncome(Number(e.target.value))}
                            className="input input-bordered w-full"
                        />
                    ) : (
                        <div className="text-2xl font-bold text-primary">
                            {formatRupiah(income)}
                        </div>
                    )}
                </div>
            </div>

            {/* Budget Allocation */}
            <div className="card card-compact bg-base-200 bg-opacity-50">
                <div className="card-body space-y-4">
                    <h3 className="card-title text-base-content">Alokasi Budget (Total: 100%)</h3>

                    <AllocationSlider
                        icon="🏠"
                        label="Needs"
                        value={needs}
                        onChange={setNeeds}
                        amount={income * (needs / 100)}
                        disabled={!editing}
                        max={100 - wants}
                        color="success"
                    />

                    <AllocationSlider
                        icon="🎮"
                        label="Wants"
                        value={wants}
                        onChange={setWants}
                        amount={income * (wants / 100)}
                        disabled={!editing}
                        max={100 - needs}
                        color="warning"
                    />

                    <AllocationSlider
                        icon="💵"
                        label="Savings"
                        value={savings}
                        onChange={() => { }}
                        amount={income * (savings / 100)}
                        disabled={true}
                        max={100}
                        color="info"
                    />

                    {editing && (
                        <button
                            onClick={handleSave}
                            className="btn btn-primary w-full"
                        >
                            Simpan Perubahan
                        </button>
                    )}
                </div>
            </div>

            {/* Tips */}
            <div className="alert alert-info">
                <span>💡</span>
                <div>
                    <div className="font-medium">Tips</div>
                    <div className="text-sm text-base-content text-opacity-80">
                        Setiap rupiah harus punya tujuan.
                        Alokasikan 50% untuk needs, 30% untuk wants, dan 20% untuk savings.
                    </div>
                </div>
            </div>
        </div>
    );
}

function AllocationSlider({
    icon,
    label,
    value,
    onChange,
    amount,
    disabled,
    max,
    color,
}: {
    icon: string;
    label: string;
    value: number;
    onChange: (v: number) => void;
    amount: number;
    disabled: boolean;
    max: number;
    color: "success" | "warning" | "info";
}) {
    return (
        <div className="space-y-2">
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                    <span>{icon}</span>
                    <span className="font-medium">{label}</span>
                </div>
                <div className="text-right">
                    <span className="font-semibold">{value}%</span>
                    <span className="text-base-content text-opacity-50 text-sm ml-2">
                        {formatRupiah(amount)}
                    </span>
                </div>
            </div>
            <input
                type="range"
                min="0"
                max={max}
                value={value}
                onChange={(e) => onChange(parseInt(e.target.value))}
                disabled={disabled}
                className={`range range-${color} w-full ${disabled ? "opacity-50" : ""}`}
            />
        </div>
    );
}
